### ISSUE TITLE
be compatible ionic 3 ?

### ISSUE THREAD

**Issue by suwat-netprom** [gandhirajan/Cordova_Hooks#1]
I have a question.
be compatible ionic 3 ?
I see in codova document.
https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/index.html#via-hooks-directory-deprecated

**Comment by gandhirajan** [comment]
@suwat-netprom  Hooks via '/hooks' directory is deprecated. Not the cordova hooks itself. In this sample I have invoked hooks via config.xml and it should work fine.
